/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetobranco;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Bulle
 */
public class MinhaSegundaTerceiraTela extends javax.swing.JFrame {

    ArrayList<Conta> contas;
    ArrayList<Funcionario> funcionarios;
    ArrayList<Pessoa> pessoas;
    public MinhaSegundaTerceiraTela() {
        initComponents();
        funcionarios = new ArrayList<>();
        contas = new ArrayList<>();
        pessoas = new ArrayList<>();
    }
    
    private void atualizaTela(){
        jComboBoxFuncionario.removeAllItems();
        jComboBoxConta.removeAllItems();
        jComboBoxContaIni.removeAllItems();
        jComboBoxContaDest.removeAllItems();
        for (Funcionario c : funcionarios){
            jComboBoxFuncionario.addItem(c);
        }
        for (Conta d : contas){
            jComboBoxConta.addItem(d);
            jComboBoxContaIni.addItem(d);
            jComboBoxContaDest.addItem(d);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        buttonGroupOperacoes = new javax.swing.ButtonGroup();
        jComboBoxConta1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jComboBoxConta = new javax.swing.JComboBox<>();
        jButtonAdicionarConta = new javax.swing.JButton();
        jButtonEditarConta = new javax.swing.JButton();
        jButtonExcluirConta = new javax.swing.JButton();
        jButtonAdicionarTitular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListConta = new javax.swing.JList<>();
        jButtonEditarTitular = new javax.swing.JButton();
        jRadioButtonDeposito = new javax.swing.JRadioButton();
        jRadioButtonTreansferencia = new javax.swing.JRadioButton();
        jRadioButtonSaque = new javax.swing.JRadioButton();
        jTextFieldValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxContaDest = new javax.swing.JComboBox<>();
        jButtonExecutar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSaldo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldLimite = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldQtdTitular = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaFuncionario = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListFuncionario = new javax.swing.JList<>();
        jComboBoxFuncionario = new javax.swing.JComboBox<>();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonSalvarFuncionario = new javax.swing.JButton();
        jButtonEditarFuncionario = new javax.swing.JButton();
        jButtonExcluirFuncionario = new javax.swing.JButton();
        jTextFieldSalario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButtonListar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jComboBoxContaIni = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jButtonLog = new javax.swing.JButton();

        jComboBoxConta1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxConta1ItemStateChanged(evt);
            }
        });
        jComboBoxConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConta1ActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxConta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxContaItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 346, -1));

        jButtonAdicionarConta.setText("Add Conta");
        jButtonAdicionarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarContaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdicionarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 56, -1, -1));

        jButtonEditarConta.setText("Edit Conta");
        jButtonEditarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarContaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 56, -1, -1));

        jButtonExcluirConta.setText("Exclui Conta");
        jButtonExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirContaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluirConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 56, -1, -1));

        jButtonAdicionarTitular.setText("Add Titular");
        jButtonAdicionarTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarTitularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdicionarTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 56, -1, -1));

        jScrollPane1.setViewportView(jListConta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 83, 346, 102));

        jButtonEditarTitular.setText("Editar Titular");
        jButtonEditarTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarTitularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 191, -1, -1));

        buttonGroupOperacoes.add(jRadioButtonDeposito);
        jRadioButtonDeposito.setText("Depósito");
        getContentPane().add(jRadioButtonDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 622, -1, -1));

        buttonGroupOperacoes.add(jRadioButtonTreansferencia);
        jRadioButtonTreansferencia.setText("Transferência");
        getContentPane().add(jRadioButtonTreansferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 622, -1, -1));

        buttonGroupOperacoes.add(jRadioButtonSaque);
        jRadioButtonSaque.setText("Saque");
        getContentPane().add(jRadioButtonSaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 622, -1, -1));
        getContentPane().add(jTextFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 691, 55, -1));

        jLabel1.setText("Valor ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 666, 40, -1));

        jLabel2.setText("Conta inicial:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 575, 100, -1));

        jComboBoxContaDest.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxContaDestItemStateChanged(evt);
            }
        });
        jComboBoxContaDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxContaDestActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxContaDest, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 690, 894, -1));

        jButtonExecutar.setText("Executar operação");
        jButtonExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 622, 712, 48));

        jLabel3.setText("Conta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 10, 58, -1));

        jLabel4.setText("Operações");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 556, 63, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 556, 898, 6));

        jTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 75, -1));

        jLabel5.setText("CPF");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 55, -1));

        jLabel6.setText("Nome");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 58, -1));

        jLabel7.setText("Endereço");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, -1));

        jLabel8.setText("Saldo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 45, -1));
        getContentPane().add(jTextFieldSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, -1));

        jLabel9.setText("Limite");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 31, -1));
        getContentPane().add(jTextFieldLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 73, -1));

        jLabel10.setText("Número");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 225, -1));
        getContentPane().add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, 220, -1));

        jLabel11.setText("QTD Titular");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 137, 67, -1));
        getContentPane().add(jTextFieldQtdTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 156, 55, -1));

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Contas"));
        jScrollPane4.setViewportView(jTextArea);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 218, 440, 190));

        jScrollPane6.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionario"));

        jTextAreaFuncionario.setColumns(20);
        jTextAreaFuncionario.setRows(5);
        jScrollPane6.setViewportView(jTextAreaFuncionario);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 272, 505, 142));

        jListFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionario"));
        jScrollPane7.setViewportView(jListFuncionario);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 505, -1));

        jComboBoxFuncionario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxFuncionarioItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 245, 505, -1));
        getContentPane().add(jTextFieldEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 108, 600, -1));
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 64, 600, -1));
        getContentPane().add(jTextFieldMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 20, 55, -1));

        jLabel12.setText("Matricula");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 0, 55, -1));

        jButtonSalvarFuncionario.setText("Salvar Funcionario");
        jButtonSalvarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 218, -1, -1));

        jButtonEditarFuncionario.setText("Editar Funcionario");
        jButtonEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 218, -1, -1));

        jButtonExcluirFuncionario.setText("Excluir Funcionario");
        jButtonExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluirFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(846, 218, -1, -1));
        getContentPane().add(jTextFieldSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 20, 55, -1));

        jLabel13.setText("Salario");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 0, 36, -1));

        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 181, -1, 31));

        jButtonExcluir.setText("Excluir Titular");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 191, -1, -1));

        jComboBoxContaIni.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxContaIniItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxContaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 591, 955, -1));

        jLabel14.setText("Destino:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 661, 53, 23));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 722, 1000, 10));

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jTextAreaLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));
        jScrollPane2.setViewportView(jTextAreaLog);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 440, 130));

        jButtonLog.setText("Log");
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxContaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxContaItemStateChanged
        // TODO add your handling code here:
        DefaultListModel<Pessoa> model = new DefaultListModel<>();
        jListConta.setModel(model);
        
        Conta auxConta = (Conta)jComboBoxConta.getSelectedItem(); 
        if(auxConta != null){
            model.addElement(null);
            for(Pessoa p : auxConta.getTitular()){
                model.addElement(p);
            }
        
        }
    }//GEN-LAST:event_jComboBoxContaItemStateChanged

    private void jButtonExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarActionPerformed
        // TODO add your handling code here:
        Double valor = Double.parseDouble(jTextFieldValor.getText());
        
        Funcionario auxFuncionarioOperacao = (Funcionario)jComboBoxFuncionario.getSelectedItem();
        Conta iniConta = (Conta)jComboBoxContaIni.getSelectedItem();
        Conta destConta = (Conta)jComboBoxContaDest.getSelectedItem();
        Pessoa titular = jListConta.getSelectedValue();
        
        short operacao = 0;
        
        if(jRadioButtonSaque.isSelected()){
            operacao = 1;
        }else if(jRadioButtonDeposito.isSelected()){
            operacao = 2;
            //iniConta.transferencia(valor, destConta, iniConta.titular.get(), auxFuncionarioOperacao);
        }else if (jRadioButtonTreansferencia.isSelected()){
            operacao = 3;
        }
        

        
        if (operacao == 1){
             
            
            if ((iniConta.getSaldo() - valor) >= (iniConta.getLimite() - (iniConta.getLimite() * 2))){                
                iniConta.setSaldo(iniConta.getSaldo() - valor);
                
            }
        }else if(operacao == 2){
            
            
            if((iniConta.getSaldo() - valor) >= (iniConta.getLimite() - (iniConta.getLimite() * 2))){
                iniConta.setSaldo(iniConta.getSaldo() + valor);
              
            }
        }else if(operacao == 3){
            //iniConta.transferencia(valor, destConta, iniConta.titular.get(), auxFuncionarioOperacao);
            
            if((iniConta.getSaldo() - valor) >= (iniConta.getLimite() - (iniConta.getLimite() * 2))){
                iniConta.setSaldo(iniConta.getSaldo() - valor);
                destConta.setSaldo(destConta.getSaldo() + valor);
              
            }
        }
        
        atualizaTela();
        
    }//GEN-LAST:event_jButtonExecutarActionPerformed

    private void jTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFActionPerformed

    private void jComboBoxFuncionarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFuncionarioItemStateChanged
        // TODO add your handling code here:
        jTextFieldNome.setText("");
        jTextFieldSaldo.setText("");
        jTextFieldCPF.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldSaldo.setText("");
        jTextFieldMatricula.setText("");

        DefaultListModel<Funcionario> model = new DefaultListModel<>();
        jListFuncionario.setModel(model);

        Funcionario auxFuncionario = (Funcionario)jComboBoxFuncionario.getSelectedItem();
        if(auxFuncionario != null){
            jTextFieldNome.setText("" + auxFuncionario.getNome());
            jTextFieldSaldo.setText("" + auxFuncionario.getSalario());
            jTextFieldMatricula.setText("" + auxFuncionario.getMatricula());
            jTextFieldCPF.setText("" + auxFuncionario.getCpf());
            jTextFieldEndereco.setText("" + auxFuncionario.getEndereco());

            model.addElement(null);

            Conta auxConta = (Conta)jComboBoxFuncionario.getSelectedItem();

            //for(Funcionario p : auxConta.getTitular()){
                //   model.addElement(p);
                //}
        }
    }//GEN-LAST:event_jComboBoxFuncionarioItemStateChanged

    private void jButtonSalvarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarFuncionarioActionPerformed
        // TODO add your handling code here:
        double salario = Double.parseDouble(jTextFieldSalario.getText());
        double matricula = Double.parseDouble(jTextFieldMatricula.getText());
        
        String cpf = jTextFieldCPF.getText();
        String nome = jTextFieldNome.getText();
        String end = jTextFieldEndereco.getText();
        
        Funcionario aux = new Funcionario(cpf, salario, nome, cpf, end);
        funcionarios.add(aux);
        
        jTextFieldNome.setText("");
        jTextFieldCPF.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldSalario.setText("");
        jTextFieldMatricula.setText("");
        
        atualizaTela();
    }//GEN-LAST:event_jButtonSalvarFuncionarioActionPerformed

    private void jButtonEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarFuncionarioActionPerformed
        // TODO add your handling code here:
        Funcionario auxFuncionario = (Funcionario)jComboBoxFuncionario.getSelectedItem();
        auxFuncionario.setEndereco(jTextFieldEndereco.getText());
        auxFuncionario.setSalario(Double.parseDouble(jTextFieldSaldo.getText()));
        auxFuncionario.setMatricula(jTextFieldMatricula.getText());
        auxFuncionario.setCpf(jTextFieldCPF.getText());
        
        jButtonEditarFuncionario.doClick();
        atualizaTela();
    }//GEN-LAST:event_jButtonEditarFuncionarioActionPerformed

    private void jButtonExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirFuncionarioActionPerformed
        // TODO add your handling code here:
        funcionarios.remove(jListFuncionario.getSelectedValuesList());
        
        atualizaTela();
    }//GEN-LAST:event_jButtonExcluirFuncionarioActionPerformed

    private void jComboBoxConta1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxConta1ItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxConta1ItemStateChanged

    private void jComboBoxConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConta1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxConta1ActionPerformed

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        // TODO add your handling code here:
        jTextArea.setText("");
        for (Conta c : contas) {
            jTextArea.append(c.toString());
        }
        for (Funcionario c : funcionarios) {
            jTextAreaFuncionario.append(c.toString());
        }
        atualizaTela();
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(jTextFieldNumero.getText());
        double saldo = Double.parseDouble(jTextFieldSaldo.getText());
        double limite = Double.parseDouble(jTextFieldLimite.getText());

        String cpf = jTextFieldCPF.getText();
        String nome = jTextFieldNome.getText();
        String end = jTextFieldEndereco.getText();
        String qtdtitular = jTextFieldQtdTitular.getText();

        Conta aux = new Conta(numero, saldo, limite, nome, end, cpf);
        contas.add(aux);

        jTextFieldNome.setText("");
        jTextFieldNumero.setText("");
        jTextFieldCPF.setText("");
        jTextFieldLimite.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldSaldo.setText("");
        jTextFieldQtdTitular.setText("");

        atualizaTela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here: 
        pessoas.remove(jListConta.getSelectedValue()); //NAO TA FUNCIONANDO
        
        jButtonListar.doClick();
        atualizaTela();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarTitularActionPerformed
        // TODO add your handling code here:
        Conta auxConta = (Conta)jComboBoxConta.getSelectedItem();
        auxConta.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
        auxConta.setSaldo(Double.parseDouble(jTextFieldSaldo.getText()));
        auxConta.setLimite(Double.parseDouble(jTextFieldLimite.getText()));
        
        jButtonListar.doClick();
        atualizaTela();
    }//GEN-LAST:event_jButtonEditarTitularActionPerformed

    private void jButtonAdicionarTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarTitularActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldNome.getText();
        String endereco = jTextFieldEndereco.getText();
        String cpf = jTextFieldCPF.getText();
        
        Conta auxConta = (Conta)jComboBoxConta.getSelectedItem();
        
        auxConta.titular.add(new Pessoa(nome, endereco, cpf));
        
        atualizaTela();
    }//GEN-LAST:event_jButtonAdicionarTitularActionPerformed

    private void jButtonAdicionarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarContaActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(jTextFieldNumero.getText());
        double saldo = Double.parseDouble(jTextFieldSaldo.getText());
        double limite = Double.parseDouble(jTextFieldLimite.getText());
        
        String cpf = jTextFieldCPF.getText();
        String nome = jTextFieldNome.getText();
        String end = jTextFieldEndereco.getText();
        String qtdtitular = jTextFieldQtdTitular.getText();
        
        Conta aux = new Conta(numero, saldo, limite, nome, end, cpf);
        contas.add(aux);
        
        jTextFieldNome.setText("");
        jTextFieldNumero.setText("");
        jTextFieldCPF.setText("");
        jTextFieldLimite.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldSaldo.setText("");
        jTextFieldQtdTitular.setText("");
        
        atualizaTela();
    }//GEN-LAST:event_jButtonAdicionarContaActionPerformed

    private void jButtonEditarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarContaActionPerformed
        // TODO add your handling code here:
        Conta auxConta = (Conta)jComboBoxConta.getSelectedItem();
        auxConta.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
        auxConta.setSaldo(Double.parseDouble(jTextFieldSaldo.getText()));
        auxConta.setLimite(Double.parseDouble(jTextFieldLimite.getText()));
        
        jButtonListar.doClick();
        atualizaTela();
    }//GEN-LAST:event_jButtonEditarContaActionPerformed

    private void jComboBoxContaIniItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxContaIniItemStateChanged
        // TODO add your handling code here:
        DefaultListModel<Pessoa> model = new DefaultListModel<>();
        jListConta.setModel(model);
        
        Conta iniConta = (Conta)jComboBoxContaIni.getSelectedItem();
        if(iniConta != null){
            model.addElement(null);
            for(Pessoa p : iniConta.getTitular()){
                model.addElement(p);
            }
        
        }
    }//GEN-LAST:event_jComboBoxContaIniItemStateChanged

    private void jComboBoxContaDestItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxContaDestItemStateChanged
        // TODO add your handling code here:
        DefaultListModel<Pessoa> model = new DefaultListModel<>();
        jListConta.setModel(model);
        
        Conta iniConta = (Conta)jComboBoxContaDest.getSelectedItem();
        if(iniConta != null){
            model.addElement(null);
            for(Pessoa p : iniConta.getTitular()){
                model.addElement(p);
            }
        
        }
    }//GEN-LAST:event_jComboBoxContaDestItemStateChanged

    private void jComboBoxContaDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxContaDestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxContaDestActionPerformed

    private void jButtonExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirContaActionPerformed
        // TODO add your handling code here:
        Conta auxConta = (Conta)jComboBoxConta.getSelectedItem();
        contas.remove(auxConta);
        jButtonListar.doClick();
        atualizaTela();
    }//GEN-LAST:event_jButtonExcluirContaActionPerformed

    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        // TODO add your handling code here:
        Conta auxConta = (Conta)jComboBoxConta.getSelectedItem();
        
        jTextAreaLog.setText(auxConta.getLog().toString());
        
    }//GEN-LAST:event_jButtonLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinhaSegundaTerceiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinhaSegundaTerceiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinhaSegundaTerceiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinhaSegundaTerceiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinhaSegundaTerceiraTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupOperacoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdicionarConta;
    private javax.swing.JButton jButtonAdicionarTitular;
    private javax.swing.JButton jButtonEditarConta;
    private javax.swing.JButton jButtonEditarFuncionario;
    private javax.swing.JButton jButtonEditarTitular;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonExcluirConta;
    private javax.swing.JButton jButtonExcluirFuncionario;
    private javax.swing.JButton jButtonExecutar;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JButton jButtonSalvarFuncionario;
    private javax.swing.JComboBox<Conta> jComboBoxConta;
    private javax.swing.JComboBox<Conta> jComboBoxConta1;
    private javax.swing.JComboBox<Conta> jComboBoxContaDest;
    private javax.swing.JComboBox<Conta> jComboBoxContaIni;
    private javax.swing.JComboBox<Funcionario> jComboBoxFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<Pessoa> jListConta;
    private javax.swing.JList<Funcionario> jListFuncionario;
    private javax.swing.JRadioButton jRadioButtonDeposito;
    private javax.swing.JRadioButton jRadioButtonSaque;
    private javax.swing.JRadioButton jRadioButtonTreansferencia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextArea jTextAreaFuncionario;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldLimite;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldQtdTitular;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JTextField jTextFieldSaldo;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
